
[package]
name = "piccolo"
version = "0.1.0"
authors = ["Zack <zackh@firemail.cc>"]

[dependencies]

[dev-dependencies]
rustyline = "1.0"

[[example]]
name = "interpreter"
path = "bin/interpreter.rs"

[[example]]
name = "repl"
path = "bin/repl.rs"

