[package]
name = "piccolo"
version = "0.2.0"
authors = ["Zack <zphixon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
pc-debug = []
fuzzer = ["pc-debug"]

[dependencies]
rustyline = "6.0.0"
downcast-rs = "1.1.1"
rand = "0.7.3"

[dev-dependencies]
clap = "2.33.0"
