
[package]
name = "piccolo"
version = "0.1.0"
authors = ["Zack <zackh@firemail.cc>"]
license = "MIT"

[dependencies]
time = "0.1"

[dev-dependencies]
rustyline = "1.0"

[[example]]
name = "interpreter"
path = "bin/interpreter.rs"

[[example]]
name = "repl"
path = "bin/repl.rs"

